Repository dmscn/debian-distro-igniter, pull requests merged in 2018-12, with the labels that each got.

#2 Extracted package arrays to separeted files
  deb_uris
  packages.apt
  packages.snap
  ubuntu-starter.sh
Labels: enhancement

#19 Created docker installation script
  .github/PULL_REQUEST_TEMPLATE.md
  docker_installation.sh
Labels: enhancement

#20 Added creation of Dracula theme config for terminator
  packages/packages.apt
  packages/packages.snap
  scripts/docker_installation.sh
  scripts/nodejs-installation.sh
  starter.sh
  static/dracula-theme-terminator
  test/test-on-container.sh
Labels: enhancement

#21 Creating Node installation script
  scripts/docker_installation.sh
  scripts/nodejs-installation.sh
  starter.sh
Labels: enhancement

#22 Created python-installation script
  scripts/python_installation.sh
Labels: enhancement

#26 Created npm global modules file
  packages/packages.global.npm
  scripts/nodejs-installation.sh
Labels: enhancement

#27 Enhancement/remove terminator dracula fullscreen
  scripts/packages_installation.sh
  static/dracula-theme-terminator
Labels: enhancement

#28 Container to test app
  Makefile
  scripts/apt-packages-installation.sh
  scripts/docker_installation.sh
  scripts/python_installation.sh
  scripts/snap-packages-installation.sh
  starter.sh
  test/Dockerfile
  test/Makefile
  test/test-on-container.sh
Labels: enhancement

#25 Upgrade starter.sh
  Makefile
  scripts/apt-packages-installation.sh
  scripts/docker_installation.sh
  scripts/snap-packages-installation.sh
  starter.sh
Labels: enhancement, good first issue

#31 Added script to install vscode extensions
  Makefile
  packages/vscode-extensions.txt
  scripts/apt-packages-installation.sh
  scripts/docker_installation.sh
  scripts/snap-packages-installation.sh
  scripts/vscode-install-extensions.sh
Labels: enhancement

#30 CLI
  .gitignore
  Makefile
  packages/packages.apt
  pycli/README.md
  pycli/__init__.py
  pycli/__main__.py
  pycli/requirements.txt
Labels: enhancement, new feature

#32 Commented feature install loop
  pycli/__main__.py
Labels: bug
